# Generated by Django 5.0.6 on 2024-07-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_blog_view_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='превью'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='view_counter',
            field=models.IntegerField(default=0, verbose_name='кол-во просмотров'),
        ),
    ]
